sudo: required
services:
    - docker

before_install:
    - docker build -t v30/complex -f ./client/Dockerfile.dev ./client

script:
    - docker run v30/complex npm test -- --coverage

after_success:
    - docker build -t v30/multi-client ./client
    - docker build -t v30/multi-nginx ./nginx
    - docker build -t v30/multi-server ./server
    - docker build -t v30/multi-worker ./worker
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push v30/multi-client
    - docker push v30/multi-nginx
    - docker push v30/multi-server
    - docker push v30/multi-worker