sudo: required
services:
    - docker

before_install:
    - docker build -t wenov3/complex -f ./client/Dockerfile.dev ./client

script:
    - docker run wenov3/complex npm test -- --coverage

after_success:
    - docker build -t wenov3/multi-client ./client
    - docker build -t wenov3/multi-nginx ./nginx
    - docker build -t wenov3/multi-server ./server
    - docker build -t wenov3/multi-worker ./worker
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push wenov3/multi-client
    - docker push wenov3/multi-nginx
    - docker push wenov3/multi-server
    - docker push wenov3/multi-worker
